---
- name: Install php-fpm and deps
  yum: name={{ item }} state=present
  with_items:
    - rh-php56
    - rh-php56-fpm
    - rh-php56-enchant
    - rh-php56-IDNA_Convert
    - rh-php56-mbstring
    - rh-php56-mysql
    - rh-php56-PHPMailer
    - rh-php56-process
    - rh-php56-simplepie
    - rh-php56-xml

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm
